### ISSUE TITLE
Application Opens, then closes.

### ISSUE THREAD

**Issue by carcarjg** [carcarjg/PPCP-AppManager#13]
I will look back and see when it starts doing that. It shows no error.. Just closes. If someone can test to see if it does it to them that would be great

**Comment by JohnSpahr** [comment]
Weird. I tried running it and experienced the same issue. My suggestion is that we comment all the code that runs when the app starts. We then uncomment each section bit by bit and test, and when it finally crashes, we'll know which part of the code is the culprit.

**Comment by carcarjg** [comment]
Fixed it on my end @JohnSpahr can you see if it works for you?

**Comment by JohnSpahr** [comment]
Yep, I'll do that now!

**Comment by JohnSpahr** [comment]
It works! Issue has been closed.
